
import controller.CalculadoraController;
import controller.EnumOperacao;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.util.Locale;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author clebe
 */
public class Calculator extends javax.swing.JFrame {

    private CalculadoraController calculadorController;
    
    private EnumOperacao ultimaOperacao;

    public Calculator() {
        initComponents();
        calculadorController = new CalculadoraController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtVisor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jBtnCE = new javax.swing.JButton();
        jBtnC = new javax.swing.JButton();
        jBtnBckSpace = new javax.swing.JButton();
        jBtnDiv = new javax.swing.JButton();
        jBtnSete = new javax.swing.JButton();
        jBtnOito = new javax.swing.JButton();
        jBtnNove = new javax.swing.JButton();
        jBtnMult = new javax.swing.JButton();
        jBtnQuatro = new javax.swing.JButton();
        jBtnCinco = new javax.swing.JButton();
        jBtnSeis = new javax.swing.JButton();
        jBtnSub = new javax.swing.JButton();
        jBtnUm = new javax.swing.JButton();
        jBtnDois = new javax.swing.JButton();
        jBtnTres = new javax.swing.JButton();
        jBtnSoma = new javax.swing.JButton();
        jBtnMaisMenos = new javax.swing.JButton();
        jBtnZero = new javax.swing.JButton();
        jBtnVirg = new javax.swing.JButton();
        jBtnIgual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculada Java");

        jTxtVisor.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        jTxtVisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtVisor.setText("0,00");

        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        jBtnCE.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnCE.setText("CE");
        jBtnCE.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCEActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCE);

        jBtnC.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnC.setText("C");
        jBtnC.setMaximumSize(new java.awt.Dimension(41, 35));
        jBtnC.setMinimumSize(new java.awt.Dimension(41, 35));
        jBtnC.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnC);

        jBtnBckSpace.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnBckSpace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backspace.png"))); // NOI18N
        jBtnBckSpace.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jBtnBckSpace);

        jBtnDiv.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnDiv.setText("/");
        jBtnDiv.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnDiv);

        jBtnSete.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnSete.setText("7");
        jBtnSete.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSeteActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSete);

        jBtnOito.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnOito.setText("8");
        jBtnOito.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOitoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnOito);

        jBtnNove.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnNove.setText("9");
        jBtnNove.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNoveActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnNove);

        jBtnMult.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnMult.setText("X");
        jBtnMult.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMultActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnMult);

        jBtnQuatro.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnQuatro.setText("4");
        jBtnQuatro.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnQuatroActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnQuatro);

        jBtnCinco.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnCinco.setText("5");
        jBtnCinco.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCincoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCinco);

        jBtnSeis.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnSeis.setText("6");
        jBtnSeis.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSeisActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSeis);

        jBtnSub.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnSub.setText("-");
        jBtnSub.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSub);

        jBtnUm.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnUm.setText("1");
        jBtnUm.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUmActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnUm);

        jBtnDois.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnDois.setText("2");
        jBtnDois.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDoisActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnDois);

        jBtnTres.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnTres.setText("3");
        jBtnTres.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTresActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnTres);

        jBtnSoma.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnSoma.setText("+");
        jBtnSoma.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSomaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSoma);

        jBtnMaisMenos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnMaisMenos.setText("+/");
        jBtnMaisMenos.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jBtnMaisMenos);

        jBtnZero.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnZero.setText("0");
        jBtnZero.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZeroActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnZero);

        jBtnVirg.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnVirg.setText(",");
        jBtnVirg.setPreferredSize(new java.awt.Dimension(0, 0));
        jBtnVirg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVirgActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnVirg);

        jBtnIgual.setBackground(new java.awt.Color(0, 102, 102));
        jBtnIgual.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jBtnIgual.setForeground(new java.awt.Color(255, 255, 255));
        jBtnIgual.setText("=");
        jBtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIgualActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnIgual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTxtVisor)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTxtVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void digita(String caractere) {
        if (jTxtVisor.getText().equals("0,00")) {
            jTxtVisor.setText(caractere);
        } else {
            if (caractere.equals(",") && jTxtVisor.getText().contains(",")) {

            } else {
                jTxtVisor.setText(jTxtVisor.getText().concat(caractere));
            }
        }
    }

    private void limpar() {
        jTxtVisor.setText("0,00");
    }

    private void jBtnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZeroActionPerformed
        if ((jTxtVisor.getText().equals("0,00"))) {

        } else {
            digita("0");
        }

    }//GEN-LAST:event_jBtnZeroActionPerformed

    private Double stringToDouble(String numero) {
        NumberFormat nf = NumberFormat.getInstance();
        Double dv = 0.0;
        try {
            dv = nf.parse(numero).doubleValue();
        } catch (Exception e) {
        }
        return dv;
    }

    private String doubleToString(Double numero) {
        if (numero != null) {
            DecimalFormat formato = new DecimalFormat("##,###,###,##0.00", new DecimalFormatSymbols(new Locale("pt", "BR")));
            formato.setParseBigDecimal(true);
            return formato.format(numero);
        }
        return "";

    }

    private void jBtnUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUmActionPerformed
        digita("1");
    }//GEN-LAST:event_jBtnUmActionPerformed

    private void jBtnDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDoisActionPerformed
        digita("2");
    }//GEN-LAST:event_jBtnDoisActionPerformed

    private void jBtnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTresActionPerformed
        digita("3");
    }//GEN-LAST:event_jBtnTresActionPerformed

    private void jBtnQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnQuatroActionPerformed
        digita("4");
    }//GEN-LAST:event_jBtnQuatroActionPerformed

    private void jBtnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCincoActionPerformed
        digita("5");
    }//GEN-LAST:event_jBtnCincoActionPerformed

    private void jBtnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSeisActionPerformed
        digita("6");
    }//GEN-LAST:event_jBtnSeisActionPerformed

    private void jBtnSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSeteActionPerformed
        digita("7");
    }//GEN-LAST:event_jBtnSeteActionPerformed

    private void jBtnOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOitoActionPerformed
        digita("8");
    }//GEN-LAST:event_jBtnOitoActionPerformed

    private void jBtnNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNoveActionPerformed
        digita("9");
    }//GEN-LAST:event_jBtnNoveActionPerformed

    private void jBtnVirgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVirgActionPerformed
        digita(",");
    }//GEN-LAST:event_jBtnVirgActionPerformed

    private void jBtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIgualActionPerformed
        calculadorController.realizarOperacao(ultimaOperacao, stringToDouble(jTxtVisor.getText()));
        jTxtVisor.setText(doubleToString(calculadorController.getTotal()));
    }//GEN-LAST:event_jBtnIgualActionPerformed

    private void jBtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCEActionPerformed
        calculadorController.zerar();
        limpar();
    }//GEN-LAST:event_jBtnCEActionPerformed

    private void jBtnSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSomaActionPerformed
        calculadorController.realizarOperacao(EnumOperacao.SOMA, stringToDouble(jTxtVisor.getText()));
        ultimaOperacao = EnumOperacao.SOMA;
        limpar();
    }//GEN-LAST:event_jBtnSomaActionPerformed

    private void jBtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivActionPerformed
        calculadorController.realizarOperacao(EnumOperacao.DIVISAO, stringToDouble(jTxtVisor.getText()));
        ultimaOperacao = EnumOperacao.DIVISAO;
        limpar();
    }//GEN-LAST:event_jBtnDivActionPerformed

    private void jBtnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMultActionPerformed
        calculadorController.realizarOperacao(EnumOperacao.MULTIPLICACAO, stringToDouble(jTxtVisor.getText()));
        ultimaOperacao = EnumOperacao.MULTIPLICACAO;
        limpar();
    }//GEN-LAST:event_jBtnMultActionPerformed

    private void jBtnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubActionPerformed
        calculadorController.realizarOperacao(EnumOperacao.SUBTRACAO, stringToDouble(jTxtVisor.getText()));
        ultimaOperacao = EnumOperacao.SUBTRACAO;
        limpar();
    }//GEN-LAST:event_jBtnSubActionPerformed

    private void jBtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCActionPerformed
        limpar();
    }//GEN-LAST:event_jBtnCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBckSpace;
    private javax.swing.JButton jBtnC;
    private javax.swing.JButton jBtnCE;
    private javax.swing.JButton jBtnCinco;
    private javax.swing.JButton jBtnDiv;
    private javax.swing.JButton jBtnDois;
    private javax.swing.JButton jBtnIgual;
    private javax.swing.JButton jBtnMaisMenos;
    private javax.swing.JButton jBtnMult;
    private javax.swing.JButton jBtnNove;
    private javax.swing.JButton jBtnOito;
    private javax.swing.JButton jBtnQuatro;
    private javax.swing.JButton jBtnSeis;
    private javax.swing.JButton jBtnSete;
    private javax.swing.JButton jBtnSoma;
    private javax.swing.JButton jBtnSub;
    private javax.swing.JButton jBtnTres;
    private javax.swing.JButton jBtnUm;
    private javax.swing.JButton jBtnVirg;
    private javax.swing.JButton jBtnZero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtVisor;
    // End of variables declaration//GEN-END:variables
}
